n_rounds = 40
penalty = 0.8
n_turns = 5

[split]
method = 'iid'
# alpha = 0.1

[learner]
n = 20
m = 2
attack = 'backdoor'
defense = 'score'

[aggregator]
n = 10
m = 1
attack = 'collusion'
defense = 'score'

[local]
dataset = 'imagenette'
model = 'resnet'
datapath = '~/data'
device = 'cuda:0'
n_epochs = 5
lr = 0.01
batch_size = 32
num_workers = 2

[db]
enable = true
user = 'wuzihou'
password = 'wuzihou'
reset = true
