algorithm = 'median'
n_rounds = 100
split = 'iid'
penalty = 0.8

[learner]
n_total = 20
n_malicious = 2
attack_type = 'label-flipped'

[aggregator]
n_total = 10
n_malicious = 1
attack_type = 'colluding'

[local]
dataset = 'fmnist'
model = 'cnn-gray'
datapath = '~/data'
device = 'cuda'
n_epochs = 5
lr = 0.001
batch_size = 32
num_workers = 2

[db]
path = 'db/result.db'
reset = true