algorithm = 'feddpr'
n_learners = 20
n_aggregators = 10
n_malicious_learners = 2
attack_type = 'gradient-flipped'
n_rounds = 40
split = 'iid'
penalty = 0.8

[local]
dataset = 'cifar10'
model = 'cnn'
datapath = '~/data'
device = 'cuda'
n_epochs = 5
lr = 0.01
batch_size = 32
num_workers = 2

[db]
path = 'db/result.db'
reset = true