n_rounds = 40
penalty = 0.8
n_turns = 5

[split]
method = 'iid'
alpha = 0.1

[learner]
n = 20
m = 0
attack = 'none'
defense = 'none'

[aggregator]
n = 10
m = 0
attack = 'none'
defense = 'none'

[local]
dataset = 'imagenette'
model = 'resnet'
datapath = '~/data'
device = 'cuda'
n_epochs = 5
lr = 0.01
batch_size = 32
num_workers = 2

[db]
enable = true
path = 'db/record.db'
reset = true