algorithm = 'fedavg'
n_rounds = 100
split = 'iid'
penalty = 0.8

[learner]
n_total = 20
n_malicious = 0
attack_type = 'gradient-flipped'

[aggregator]
n_total = 1
n_malicious = 0
attack_type = 'gradient-flipped'

[local]
dataset = 'fmnist'
model = 'cnn-gray'
datapath = '~/data'
device = 'cuda'
n_epochs = 3
lr = 0.01
batch_size = 32
num_workers = 2

[db]
path = 'db/result.db'
reset = true